CREATE DATABASE SITIO_CENTRAL
USE SITIO_CENTRAL

CREATE TABLE ESQUEMA_LOCALIZACION(
	IDFRAGMENTO BIGINT NOT NULL,
	NOMBRE_FRAG VARCHAR(50) NOT NULL,
	NOMBRE_TABLA VARCHAR(50) NOT NULL,
	TIPO_FRAG VARCHAR(50) NOT NULL,
	SITIO VARCHAR(10) NOT NULL,
	CONDICION VARCHAR(100),

	CONSTRAINT PK_IDFRAG PRIMARY KEY(IDFRAGMENTO)
)

INSERT INTO ESQUEMA_LOCALIZACION VALUES(1, 'CLIENTE1', 'CLIENTE', 'NULL', '1',NULL);
INSERT INTO ESQUEMA_LOCALIZACION VALUES(2, 'LINEA1', 'LINEA', 'VERTICAL', '1',NULL);
INSERT INTO ESQUEMA_LOCALIZACION VALUES(3, 'LINEA2', 'LINEA', 'VERTICAL', '2',NULL);
INSERT INTO ESQUEMA_LOCALIZACION VALUES(4, 'DOMICILIO1', 'DOMICILIO', 'HORIZONTAL', '1','dirActual=1');
INSERT INTO ESQUEMA_LOCALIZACION VALUES(5, 'DOMICILIO2', 'DOMICILIO', 'HORIZONTAL', '2','dirActual=0');
INSERT INTO ESQUEMA_LOCALIZACION VALUES(6, 'RES_CLIENTE1', 'RES_CLIENTE', 'HORIZONTAL', '1','Resultado=Excelente OR Bueno OR Regular');
INSERT INTO ESQUEMA_LOCALIZACION VALUES(7, 'RES_CLIENTE2', 'RES_CLIENTE', 'HORIZONTAL', '2','Resultado=Diferida');
INSERT INTO ESQUEMA_LOCALIZACION VALUES(8, 'ACTIVACION1', 'ACTIVACION', 'REPLICA', '1',NULL);
INSERT INTO ESQUEMA_LOCALIZACION VALUES(9, 'ACTIVACION2', 'ACTIVACION', 'REPLICA', '2',NULL);
INSERT INTO ESQUEMA_LOCALIZACION VALUES(10, 'VENDEDOR1', 'VENDEDOR', 'REPLICA', '1',NULL);
INSERT INTO ESQUEMA_LOCALIZACION VALUES(11, 'VENDEDOR2', 'VENDEDOR', 'REPLICA', '2',NULL);

CREATE TABLE ATRIBUTOS(
	IDFRAGMENTO BIGINT,
	NOMBRE_ATRIBUTO VARCHAR(50),

	CONSTRAINT FK_IDFRAG FOREIGN KEY (IDFRAGMENTO)
		REFERENCES ESQUEMA_LOCALIZACION(IDFRAGMENTO)

)

INSERT INTO ATRIBUTOS VALUES(1, 'IDCLIENTE');
INSERT INTO ATRIBUTOS VALUES(1, 'NOMBRE');
INSERT INTO ATRIBUTOS VALUES(1, 'APELLIDOP');
INSERT INTO ATRIBUTOS VALUES(1, 'APELLIDOM');
INSERT INTO ATRIBUTOS VALUES(1, 'FECHANAC');
INSERT INTO ATRIBUTOS VALUES(1, 'NUMCONTACTO');


INSERT INTO ATRIBUTOS VALUES(2, 'IDLINEA');
INSERT INTO ATRIBUTOS VALUES(2, 'IDCLIENTE');

INSERT INTO ATRIBUTOS VALUES('3', 'IDLINEA');
INSERT INTO ATRIBUTOS VALUES('3', 'NUMCELULAR');
INSERT INTO ATRIBUTOS VALUES('3', 'NUMCUENTA');
INSERT INTO ATRIBUTOS VALUES('3', 'NUMLINEA');
INSERT INTO ATRIBUTOS VALUES('3', 'FECHACORTE');
INSERT INTO ATRIBUTOS VALUES('3', 'FECHAPAGO');
INSERT INTO ATRIBUTOS VALUES('3', 'FECHACHEQUEO');
INSERT INTO ATRIBUTOS VALUES('3', 'ESTATUS');
INSERT INTO ATRIBUTOS VALUES('3', 'ADEUDO');

INSERT INTO ATRIBUTOS VALUES('4', 'IDDOMICILIO');
INSERT INTO ATRIBUTOS VALUES('4', 'IDCLIENTE');
INSERT INTO ATRIBUTOS VALUES('4', 'DIRACTUAL');
INSERT INTO ATRIBUTOS VALUES('4', 'CALLE');
INSERT INTO ATRIBUTOS VALUES('4', 'NUMINT');
INSERT INTO ATRIBUTOS VALUES('4', 'NUMEXT');
INSERT INTO ATRIBUTOS VALUES('4', 'CP');
INSERT INTO ATRIBUTOS VALUES('4', 'COLONIA');
INSERT INTO ATRIBUTOS VALUES('4', 'MUNICIPIO');

INSERT INTO ATRIBUTOS VALUES('5', 'IDDOMICILIO');
INSERT INTO ATRIBUTOS VALUES('5', 'IDCLIENTE');
INSERT INTO ATRIBUTOS VALUES('5', 'DIRACTUAL');
INSERT INTO ATRIBUTOS VALUES('5', 'CALLE');
INSERT INTO ATRIBUTOS VALUES('5', 'NUMINT');
INSERT INTO ATRIBUTOS VALUES('5', 'NUMEXT');
INSERT INTO ATRIBUTOS VALUES('5', 'COLONIA');
INSERT INTO ATRIBUTOS VALUES('5', 'MUNICIPIO');

INSERT INTO ATRIBUTOS VALUES('6', 'IDEVAR');
INSERT INTO ATRIBUTOS VALUES('6', 'IDVENDEDOR');
INSERT INTO ATRIBUTOS VALUES('6', 'IDCLIENTE');
INSERT INTO ATRIBUTOS VALUES('6', 'FOLIOEVAR');
INSERT INTO ATRIBUTOS VALUES('6', 'FECHAEVAR');
INSERT INTO ATRIBUTOS VALUES('6', 'ASESOR');
INSERT INTO ATRIBUTOS VALUES('6', 'RESULTADO');
INSERT INTO ATRIBUTOS VALUES('6', 'OBSERVACIONES');
INSERT INTO ATRIBUTOS VALUES('6', 'RFC_EVAR');

INSERT INTO ATRIBUTOS VALUES('7', 'IDEVAR');
INSERT INTO ATRIBUTOS VALUES('7', 'IDVENDEDOR');
INSERT INTO ATRIBUTOS VALUES('7', 'IDCLIENTE');
INSERT INTO ATRIBUTOS VALUES('7', 'FOLIOEVAR');
INSERT INTO ATRIBUTOS VALUES('7', 'FECHAEVAR');
INSERT INTO ATRIBUTOS VALUES('7', 'ASESOR');
INSERT INTO ATRIBUTOS VALUES('7', 'RESULTADO');
INSERT INTO ATRIBUTOS VALUES('7', 'OBSERVACIONES');
INSERT INTO ATRIBUTOS VALUES('7', 'RFC_EVAR');

INSERT INTO ATRIBUTOS VALUES('8', 'IDACTIVACION');
INSERT INTO ATRIBUTOS VALUES('8', 'IDLINEA');
INSERT INTO ATRIBUTOS VALUES('8', 'FOLIOTALM');
INSERT INTO ATRIBUTOS VALUES('8', 'FOLIORUNNING');
INSERT INTO ATRIBUTOS VALUES('8', 'FOLIOSISACT');
INSERT INTO ATRIBUTOS VALUES('8', 'FECHAACTIVACION');

INSERT INTO ATRIBUTOS VALUES('9', 'IDACTIVACION');
INSERT INTO ATRIBUTOS VALUES('9', 'IDLINEA');
INSERT INTO ATRIBUTOS VALUES('9', 'FOLIOTALM');
INSERT INTO ATRIBUTOS VALUES('9', 'FOLIORUNNING');
INSERT INTO ATRIBUTOS VALUES('9', 'FOLIOSISACT');
INSERT INTO ATRIBUTOS VALUES('9', 'FECHAACTIVACION');

INSERT INTO ATRIBUTOS VALUES('10', 'IDVENDEDOR');
INSERT INTO ATRIBUTOS VALUES('10', 'NOMBRE');
INSERT INTO ATRIBUTOS VALUES('10', 'CELULAR');

INSERT INTO ATRIBUTOS VALUES('11', 'IDVENDEDOR');
INSERT INTO ATRIBUTOS VALUES('11', 'NOMBRE');
INSERT INTO ATRIBUTOS VALUES('11', 'CELULAR');

SELECT A.IDFRAGMENTO, A.NOMBRE_ATRIBUTO
FROM ATRIBUTOS AS A, ESQUEMA_LOCALIZACION AS E
WHERE E.IDFRAGMENTO = A.IDFRAGMENTO
AND E.IDFRAGMENTO=1

SELECT COUNT(A.NOMBRE_ATRIBUTO) AS 'CUENTA'
FROM ATRIBUTOS AS A
WHERE A.IDFRAGMENTO=1 


